#!/usr/bin/env ruby -I:lib
require 'lib/client/rayd8or.rb'

client = Rayd8or.new
DRb.start_service 
server = DRbObject.new(nil, "druby://localhost:5501") 
server.subscribe_to_all(client) 
DRb.thread.join
